//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAP.UserCard.Web {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Init", Namespace="http://hap.codeplex.com/")]
    [System.SerializableAttribute()]
    public partial class Init : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentGroupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ADConStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentEmailFormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StudentGroupName {
            get {
                return this.StudentGroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentGroupNameField, value) != true)) {
                    this.StudentGroupNameField = value;
                    this.RaisePropertyChanged("StudentGroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ADConString {
            get {
                return this.ADConStringField;
            }
            set {
                if ((object.ReferenceEquals(this.ADConStringField, value) != true)) {
                    this.ADConStringField = value;
                    this.RaisePropertyChanged("ADConString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string StudentEmailFormat {
            get {
                return this.StudentEmailFormatField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentEmailFormatField, value) != true)) {
                    this.StudentEmailFormatField = value;
                    this.RaisePropertyChanged("StudentEmailFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Department", Namespace="http://hap.codeplex.com/")]
    [System.SerializableAttribute()]
    public partial class Department : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Form", Namespace="http://hap.codeplex.com/")]
    [System.SerializableAttribute()]
    public partial class Form : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OUField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string OU {
            get {
                return this.OUField;
            }
            set {
                if ((object.ReferenceEquals(this.OUField, value) != true)) {
                    this.OUField = value;
                    this.RaisePropertyChanged("OU");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuotaInfo", Namespace="http://hap.codeplex.com/")]
    [System.SerializableAttribute()]
    public partial class QuotaInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HAP.UserCard.Web.ExtensionDataObject ExtensionData1Field;
        
        private double FreeField;
        
        private double TotalField;
        
        private double UsedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public HAP.UserCard.Web.ExtensionDataObject ExtensionData1 {
            get {
                return this.ExtensionData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionData1Field, value) != true)) {
                    this.ExtensionData1Field = value;
                    this.RaisePropertyChanged("ExtensionData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Free {
            get {
                return this.FreeField;
            }
            set {
                if ((this.FreeField.Equals(value) != true)) {
                    this.FreeField = value;
                    this.RaisePropertyChanged("Free");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Used {
            get {
                return this.UsedField;
            }
            set {
                if ((this.UsedField.Equals(value) != true)) {
                    this.UsedField = value;
                    this.RaisePropertyChanged("Used");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExtensionDataObject", Namespace="http://hap.codeplex.com/")]
    [System.SerializableAttribute()]
    public partial class ExtensionDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://hap.codeplex.com/", ConfigurationName="Web.apiSoap")]
    public interface apiSoap {
        
        // CODEGEN: Generating message contract since element name getInitResult from namespace http://hap.codeplex.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://hap.codeplex.com/getInit", ReplyAction="*")]
        HAP.UserCard.Web.getInitResponse getInit(HAP.UserCard.Web.getInitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://hap.codeplex.com/getInit", ReplyAction="*")]
        System.IAsyncResult BegingetInit(HAP.UserCard.Web.getInitRequest request, System.AsyncCallback callback, object asyncState);
        
        HAP.UserCard.Web.getInitResponse EndgetInit(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name getDepartmentsResult from namespace http://hap.codeplex.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://hap.codeplex.com/getDepartments", ReplyAction="*")]
        HAP.UserCard.Web.getDepartmentsResponse getDepartments(HAP.UserCard.Web.getDepartmentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://hap.codeplex.com/getDepartments", ReplyAction="*")]
        System.IAsyncResult BegingetDepartments(HAP.UserCard.Web.getDepartmentsRequest request, System.AsyncCallback callback, object asyncState);
        
        HAP.UserCard.Web.getDepartmentsResponse EndgetDepartments(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name getFormsResult from namespace http://hap.codeplex.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://hap.codeplex.com/getForms", ReplyAction="*")]
        HAP.UserCard.Web.getFormsResponse getForms(HAP.UserCard.Web.getFormsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://hap.codeplex.com/getForms", ReplyAction="*")]
        System.IAsyncResult BegingetForms(HAP.UserCard.Web.getFormsRequest request, System.AsyncCallback callback, object asyncState);
        
        HAP.UserCard.Web.getFormsResponse EndgetForms(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name ou from namespace http://hap.codeplex.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://hap.codeplex.com/getFormsIn", ReplyAction="*")]
        HAP.UserCard.Web.getFormsInResponse getFormsIn(HAP.UserCard.Web.getFormsInRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://hap.codeplex.com/getFormsIn", ReplyAction="*")]
        System.IAsyncResult BegingetFormsIn(HAP.UserCard.Web.getFormsInRequest request, System.AsyncCallback callback, object asyncState);
        
        HAP.UserCard.Web.getFormsInResponse EndgetFormsIn(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name username from namespace http://hap.codeplex.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://hap.codeplex.com/ResetPassword", ReplyAction="*")]
        HAP.UserCard.Web.ResetPasswordResponse ResetPassword(HAP.UserCard.Web.ResetPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://hap.codeplex.com/ResetPassword", ReplyAction="*")]
        System.IAsyncResult BeginResetPassword(HAP.UserCard.Web.ResetPasswordRequest request, System.AsyncCallback callback, object asyncState);
        
        HAP.UserCard.Web.ResetPasswordResponse EndResetPassword(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name username from namespace http://hap.codeplex.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://hap.codeplex.com/GetFreeSpacePercentage", ReplyAction="*")]
        HAP.UserCard.Web.GetFreeSpacePercentageResponse GetFreeSpacePercentage(HAP.UserCard.Web.GetFreeSpacePercentageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://hap.codeplex.com/GetFreeSpacePercentage", ReplyAction="*")]
        System.IAsyncResult BeginGetFreeSpacePercentage(HAP.UserCard.Web.GetFreeSpacePercentageRequest request, System.AsyncCallback callback, object asyncState);
        
        HAP.UserCard.Web.GetFreeSpacePercentageResponse EndGetFreeSpacePercentage(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getInit", Namespace="http://hap.codeplex.com/", Order=0)]
        public HAP.UserCard.Web.getInitRequestBody Body;
        
        public getInitRequest() {
        }
        
        public getInitRequest(HAP.UserCard.Web.getInitRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getInitRequestBody {
        
        public getInitRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getInitResponse", Namespace="http://hap.codeplex.com/", Order=0)]
        public HAP.UserCard.Web.getInitResponseBody Body;
        
        public getInitResponse() {
        }
        
        public getInitResponse(HAP.UserCard.Web.getInitResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://hap.codeplex.com/")]
    public partial class getInitResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HAP.UserCard.Web.Init getInitResult;
        
        public getInitResponseBody() {
        }
        
        public getInitResponseBody(HAP.UserCard.Web.Init getInitResult) {
            this.getInitResult = getInitResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDepartmentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDepartments", Namespace="http://hap.codeplex.com/", Order=0)]
        public HAP.UserCard.Web.getDepartmentsRequestBody Body;
        
        public getDepartmentsRequest() {
        }
        
        public getDepartmentsRequest(HAP.UserCard.Web.getDepartmentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getDepartmentsRequestBody {
        
        public getDepartmentsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDepartmentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDepartmentsResponse", Namespace="http://hap.codeplex.com/", Order=0)]
        public HAP.UserCard.Web.getDepartmentsResponseBody Body;
        
        public getDepartmentsResponse() {
        }
        
        public getDepartmentsResponse(HAP.UserCard.Web.getDepartmentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://hap.codeplex.com/")]
    public partial class getDepartmentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HAP.UserCard.Web.Department[] getDepartmentsResult;
        
        public getDepartmentsResponseBody() {
        }
        
        public getDepartmentsResponseBody(HAP.UserCard.Web.Department[] getDepartmentsResult) {
            this.getDepartmentsResult = getDepartmentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFormsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getForms", Namespace="http://hap.codeplex.com/", Order=0)]
        public HAP.UserCard.Web.getFormsRequestBody Body;
        
        public getFormsRequest() {
        }
        
        public getFormsRequest(HAP.UserCard.Web.getFormsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getFormsRequestBody {
        
        public getFormsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFormsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFormsResponse", Namespace="http://hap.codeplex.com/", Order=0)]
        public HAP.UserCard.Web.getFormsResponseBody Body;
        
        public getFormsResponse() {
        }
        
        public getFormsResponse(HAP.UserCard.Web.getFormsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://hap.codeplex.com/")]
    public partial class getFormsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HAP.UserCard.Web.Form[] getFormsResult;
        
        public getFormsResponseBody() {
        }
        
        public getFormsResponseBody(HAP.UserCard.Web.Form[] getFormsResult) {
            this.getFormsResult = getFormsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFormsInRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFormsIn", Namespace="http://hap.codeplex.com/", Order=0)]
        public HAP.UserCard.Web.getFormsInRequestBody Body;
        
        public getFormsInRequest() {
        }
        
        public getFormsInRequest(HAP.UserCard.Web.getFormsInRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://hap.codeplex.com/")]
    public partial class getFormsInRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ou;
        
        public getFormsInRequestBody() {
        }
        
        public getFormsInRequestBody(string ou) {
            this.ou = ou;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFormsInResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFormsInResponse", Namespace="http://hap.codeplex.com/", Order=0)]
        public HAP.UserCard.Web.getFormsInResponseBody Body;
        
        public getFormsInResponse() {
        }
        
        public getFormsInResponse(HAP.UserCard.Web.getFormsInResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://hap.codeplex.com/")]
    public partial class getFormsInResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HAP.UserCard.Web.Form[] getFormsInResult;
        
        public getFormsInResponseBody() {
        }
        
        public getFormsInResponseBody(HAP.UserCard.Web.Form[] getFormsInResult) {
            this.getFormsInResult = getFormsInResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResetPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResetPassword", Namespace="http://hap.codeplex.com/", Order=0)]
        public HAP.UserCard.Web.ResetPasswordRequestBody Body;
        
        public ResetPasswordRequest() {
        }
        
        public ResetPasswordRequest(HAP.UserCard.Web.ResetPasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://hap.codeplex.com/")]
    public partial class ResetPasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public ResetPasswordRequestBody() {
        }
        
        public ResetPasswordRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResetPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResetPasswordResponse", Namespace="http://hap.codeplex.com/", Order=0)]
        public HAP.UserCard.Web.ResetPasswordResponseBody Body;
        
        public ResetPasswordResponse() {
        }
        
        public ResetPasswordResponse(HAP.UserCard.Web.ResetPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://hap.codeplex.com/")]
    public partial class ResetPasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ResetPasswordResult;
        
        public ResetPasswordResponseBody() {
        }
        
        public ResetPasswordResponseBody(string ResetPasswordResult) {
            this.ResetPasswordResult = ResetPasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFreeSpacePercentageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFreeSpacePercentage", Namespace="http://hap.codeplex.com/", Order=0)]
        public HAP.UserCard.Web.GetFreeSpacePercentageRequestBody Body;
        
        public GetFreeSpacePercentageRequest() {
        }
        
        public GetFreeSpacePercentageRequest(HAP.UserCard.Web.GetFreeSpacePercentageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://hap.codeplex.com/")]
    public partial class GetFreeSpacePercentageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userhome;
        
        public GetFreeSpacePercentageRequestBody() {
        }
        
        public GetFreeSpacePercentageRequestBody(string username, string userhome) {
            this.username = username;
            this.userhome = userhome;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFreeSpacePercentageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFreeSpacePercentageResponse", Namespace="http://hap.codeplex.com/", Order=0)]
        public HAP.UserCard.Web.GetFreeSpacePercentageResponseBody Body;
        
        public GetFreeSpacePercentageResponse() {
        }
        
        public GetFreeSpacePercentageResponse(HAP.UserCard.Web.GetFreeSpacePercentageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://hap.codeplex.com/")]
    public partial class GetFreeSpacePercentageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HAP.UserCard.Web.QuotaInfo GetFreeSpacePercentageResult;
        
        public GetFreeSpacePercentageResponseBody() {
        }
        
        public GetFreeSpacePercentageResponseBody(HAP.UserCard.Web.QuotaInfo GetFreeSpacePercentageResult) {
            this.GetFreeSpacePercentageResult = GetFreeSpacePercentageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface apiSoapChannel : HAP.UserCard.Web.apiSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getInitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getInitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HAP.UserCard.Web.Init Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HAP.UserCard.Web.Init)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getDepartmentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getDepartmentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HAP.UserCard.Web.Department[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HAP.UserCard.Web.Department[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getFormsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getFormsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HAP.UserCard.Web.Form[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HAP.UserCard.Web.Form[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getFormsInCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getFormsInCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HAP.UserCard.Web.Form[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HAP.UserCard.Web.Form[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ResetPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ResetPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetFreeSpacePercentageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetFreeSpacePercentageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HAP.UserCard.Web.QuotaInfo Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HAP.UserCard.Web.QuotaInfo)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class apiSoapClient : System.ServiceModel.ClientBase<HAP.UserCard.Web.apiSoap>, HAP.UserCard.Web.apiSoap {
        
        private BeginOperationDelegate onBegingetInitDelegate;
        
        private EndOperationDelegate onEndgetInitDelegate;
        
        private System.Threading.SendOrPostCallback ongetInitCompletedDelegate;
        
        private BeginOperationDelegate onBegingetDepartmentsDelegate;
        
        private EndOperationDelegate onEndgetDepartmentsDelegate;
        
        private System.Threading.SendOrPostCallback ongetDepartmentsCompletedDelegate;
        
        private BeginOperationDelegate onBegingetFormsDelegate;
        
        private EndOperationDelegate onEndgetFormsDelegate;
        
        private System.Threading.SendOrPostCallback ongetFormsCompletedDelegate;
        
        private BeginOperationDelegate onBegingetFormsInDelegate;
        
        private EndOperationDelegate onEndgetFormsInDelegate;
        
        private System.Threading.SendOrPostCallback ongetFormsInCompletedDelegate;
        
        private BeginOperationDelegate onBeginResetPasswordDelegate;
        
        private EndOperationDelegate onEndResetPasswordDelegate;
        
        private System.Threading.SendOrPostCallback onResetPasswordCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetFreeSpacePercentageDelegate;
        
        private EndOperationDelegate onEndGetFreeSpacePercentageDelegate;
        
        private System.Threading.SendOrPostCallback onGetFreeSpacePercentageCompletedDelegate;
        
        public apiSoapClient() {
        }
        
        public apiSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public apiSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public apiSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public apiSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<getInitCompletedEventArgs> getInitCompleted;
        
        public event System.EventHandler<getDepartmentsCompletedEventArgs> getDepartmentsCompleted;
        
        public event System.EventHandler<getFormsCompletedEventArgs> getFormsCompleted;
        
        public event System.EventHandler<getFormsInCompletedEventArgs> getFormsInCompleted;
        
        public event System.EventHandler<ResetPasswordCompletedEventArgs> ResetPasswordCompleted;
        
        public event System.EventHandler<GetFreeSpacePercentageCompletedEventArgs> GetFreeSpacePercentageCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HAP.UserCard.Web.getInitResponse HAP.UserCard.Web.apiSoap.getInit(HAP.UserCard.Web.getInitRequest request) {
            return base.Channel.getInit(request);
        }
        
        public HAP.UserCard.Web.Init getInit() {
            HAP.UserCard.Web.getInitRequest inValue = new HAP.UserCard.Web.getInitRequest();
            inValue.Body = new HAP.UserCard.Web.getInitRequestBody();
            HAP.UserCard.Web.getInitResponse retVal = ((HAP.UserCard.Web.apiSoap)(this)).getInit(inValue);
            return retVal.Body.getInitResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HAP.UserCard.Web.apiSoap.BegingetInit(HAP.UserCard.Web.getInitRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetInit(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegingetInit(System.AsyncCallback callback, object asyncState) {
            HAP.UserCard.Web.getInitRequest inValue = new HAP.UserCard.Web.getInitRequest();
            inValue.Body = new HAP.UserCard.Web.getInitRequestBody();
            return ((HAP.UserCard.Web.apiSoap)(this)).BegingetInit(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HAP.UserCard.Web.getInitResponse HAP.UserCard.Web.apiSoap.EndgetInit(System.IAsyncResult result) {
            return base.Channel.EndgetInit(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public HAP.UserCard.Web.Init EndgetInit(System.IAsyncResult result) {
            HAP.UserCard.Web.getInitResponse retVal = ((HAP.UserCard.Web.apiSoap)(this)).EndgetInit(result);
            return retVal.Body.getInitResult;
        }
        
        private System.IAsyncResult OnBegingetInit(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BegingetInit(callback, asyncState);
        }
        
        private object[] OnEndgetInit(System.IAsyncResult result) {
            HAP.UserCard.Web.Init retVal = this.EndgetInit(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetInitCompleted(object state) {
            if ((this.getInitCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getInitCompleted(this, new getInitCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getInitAsync() {
            this.getInitAsync(null);
        }
        
        public void getInitAsync(object userState) {
            if ((this.onBegingetInitDelegate == null)) {
                this.onBegingetInitDelegate = new BeginOperationDelegate(this.OnBegingetInit);
            }
            if ((this.onEndgetInitDelegate == null)) {
                this.onEndgetInitDelegate = new EndOperationDelegate(this.OnEndgetInit);
            }
            if ((this.ongetInitCompletedDelegate == null)) {
                this.ongetInitCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetInitCompleted);
            }
            base.InvokeAsync(this.onBegingetInitDelegate, null, this.onEndgetInitDelegate, this.ongetInitCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HAP.UserCard.Web.getDepartmentsResponse HAP.UserCard.Web.apiSoap.getDepartments(HAP.UserCard.Web.getDepartmentsRequest request) {
            return base.Channel.getDepartments(request);
        }
        
        public HAP.UserCard.Web.Department[] getDepartments() {
            HAP.UserCard.Web.getDepartmentsRequest inValue = new HAP.UserCard.Web.getDepartmentsRequest();
            inValue.Body = new HAP.UserCard.Web.getDepartmentsRequestBody();
            HAP.UserCard.Web.getDepartmentsResponse retVal = ((HAP.UserCard.Web.apiSoap)(this)).getDepartments(inValue);
            return retVal.Body.getDepartmentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HAP.UserCard.Web.apiSoap.BegingetDepartments(HAP.UserCard.Web.getDepartmentsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetDepartments(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegingetDepartments(System.AsyncCallback callback, object asyncState) {
            HAP.UserCard.Web.getDepartmentsRequest inValue = new HAP.UserCard.Web.getDepartmentsRequest();
            inValue.Body = new HAP.UserCard.Web.getDepartmentsRequestBody();
            return ((HAP.UserCard.Web.apiSoap)(this)).BegingetDepartments(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HAP.UserCard.Web.getDepartmentsResponse HAP.UserCard.Web.apiSoap.EndgetDepartments(System.IAsyncResult result) {
            return base.Channel.EndgetDepartments(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public HAP.UserCard.Web.Department[] EndgetDepartments(System.IAsyncResult result) {
            HAP.UserCard.Web.getDepartmentsResponse retVal = ((HAP.UserCard.Web.apiSoap)(this)).EndgetDepartments(result);
            return retVal.Body.getDepartmentsResult;
        }
        
        private System.IAsyncResult OnBegingetDepartments(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BegingetDepartments(callback, asyncState);
        }
        
        private object[] OnEndgetDepartments(System.IAsyncResult result) {
            HAP.UserCard.Web.Department[] retVal = this.EndgetDepartments(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetDepartmentsCompleted(object state) {
            if ((this.getDepartmentsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getDepartmentsCompleted(this, new getDepartmentsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getDepartmentsAsync() {
            this.getDepartmentsAsync(null);
        }
        
        public void getDepartmentsAsync(object userState) {
            if ((this.onBegingetDepartmentsDelegate == null)) {
                this.onBegingetDepartmentsDelegate = new BeginOperationDelegate(this.OnBegingetDepartments);
            }
            if ((this.onEndgetDepartmentsDelegate == null)) {
                this.onEndgetDepartmentsDelegate = new EndOperationDelegate(this.OnEndgetDepartments);
            }
            if ((this.ongetDepartmentsCompletedDelegate == null)) {
                this.ongetDepartmentsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetDepartmentsCompleted);
            }
            base.InvokeAsync(this.onBegingetDepartmentsDelegate, null, this.onEndgetDepartmentsDelegate, this.ongetDepartmentsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HAP.UserCard.Web.getFormsResponse HAP.UserCard.Web.apiSoap.getForms(HAP.UserCard.Web.getFormsRequest request) {
            return base.Channel.getForms(request);
        }
        
        public HAP.UserCard.Web.Form[] getForms() {
            HAP.UserCard.Web.getFormsRequest inValue = new HAP.UserCard.Web.getFormsRequest();
            inValue.Body = new HAP.UserCard.Web.getFormsRequestBody();
            HAP.UserCard.Web.getFormsResponse retVal = ((HAP.UserCard.Web.apiSoap)(this)).getForms(inValue);
            return retVal.Body.getFormsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HAP.UserCard.Web.apiSoap.BegingetForms(HAP.UserCard.Web.getFormsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetForms(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegingetForms(System.AsyncCallback callback, object asyncState) {
            HAP.UserCard.Web.getFormsRequest inValue = new HAP.UserCard.Web.getFormsRequest();
            inValue.Body = new HAP.UserCard.Web.getFormsRequestBody();
            return ((HAP.UserCard.Web.apiSoap)(this)).BegingetForms(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HAP.UserCard.Web.getFormsResponse HAP.UserCard.Web.apiSoap.EndgetForms(System.IAsyncResult result) {
            return base.Channel.EndgetForms(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public HAP.UserCard.Web.Form[] EndgetForms(System.IAsyncResult result) {
            HAP.UserCard.Web.getFormsResponse retVal = ((HAP.UserCard.Web.apiSoap)(this)).EndgetForms(result);
            return retVal.Body.getFormsResult;
        }
        
        private System.IAsyncResult OnBegingetForms(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BegingetForms(callback, asyncState);
        }
        
        private object[] OnEndgetForms(System.IAsyncResult result) {
            HAP.UserCard.Web.Form[] retVal = this.EndgetForms(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetFormsCompleted(object state) {
            if ((this.getFormsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getFormsCompleted(this, new getFormsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getFormsAsync() {
            this.getFormsAsync(null);
        }
        
        public void getFormsAsync(object userState) {
            if ((this.onBegingetFormsDelegate == null)) {
                this.onBegingetFormsDelegate = new BeginOperationDelegate(this.OnBegingetForms);
            }
            if ((this.onEndgetFormsDelegate == null)) {
                this.onEndgetFormsDelegate = new EndOperationDelegate(this.OnEndgetForms);
            }
            if ((this.ongetFormsCompletedDelegate == null)) {
                this.ongetFormsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetFormsCompleted);
            }
            base.InvokeAsync(this.onBegingetFormsDelegate, null, this.onEndgetFormsDelegate, this.ongetFormsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HAP.UserCard.Web.getFormsInResponse HAP.UserCard.Web.apiSoap.getFormsIn(HAP.UserCard.Web.getFormsInRequest request) {
            return base.Channel.getFormsIn(request);
        }
        
        public HAP.UserCard.Web.Form[] getFormsIn(string ou) {
            HAP.UserCard.Web.getFormsInRequest inValue = new HAP.UserCard.Web.getFormsInRequest();
            inValue.Body = new HAP.UserCard.Web.getFormsInRequestBody();
            inValue.Body.ou = ou;
            HAP.UserCard.Web.getFormsInResponse retVal = ((HAP.UserCard.Web.apiSoap)(this)).getFormsIn(inValue);
            return retVal.Body.getFormsInResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HAP.UserCard.Web.apiSoap.BegingetFormsIn(HAP.UserCard.Web.getFormsInRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetFormsIn(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegingetFormsIn(string ou, System.AsyncCallback callback, object asyncState) {
            HAP.UserCard.Web.getFormsInRequest inValue = new HAP.UserCard.Web.getFormsInRequest();
            inValue.Body = new HAP.UserCard.Web.getFormsInRequestBody();
            inValue.Body.ou = ou;
            return ((HAP.UserCard.Web.apiSoap)(this)).BegingetFormsIn(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HAP.UserCard.Web.getFormsInResponse HAP.UserCard.Web.apiSoap.EndgetFormsIn(System.IAsyncResult result) {
            return base.Channel.EndgetFormsIn(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public HAP.UserCard.Web.Form[] EndgetFormsIn(System.IAsyncResult result) {
            HAP.UserCard.Web.getFormsInResponse retVal = ((HAP.UserCard.Web.apiSoap)(this)).EndgetFormsIn(result);
            return retVal.Body.getFormsInResult;
        }
        
        private System.IAsyncResult OnBegingetFormsIn(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string ou = ((string)(inValues[0]));
            return this.BegingetFormsIn(ou, callback, asyncState);
        }
        
        private object[] OnEndgetFormsIn(System.IAsyncResult result) {
            HAP.UserCard.Web.Form[] retVal = this.EndgetFormsIn(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetFormsInCompleted(object state) {
            if ((this.getFormsInCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getFormsInCompleted(this, new getFormsInCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getFormsInAsync(string ou) {
            this.getFormsInAsync(ou, null);
        }
        
        public void getFormsInAsync(string ou, object userState) {
            if ((this.onBegingetFormsInDelegate == null)) {
                this.onBegingetFormsInDelegate = new BeginOperationDelegate(this.OnBegingetFormsIn);
            }
            if ((this.onEndgetFormsInDelegate == null)) {
                this.onEndgetFormsInDelegate = new EndOperationDelegate(this.OnEndgetFormsIn);
            }
            if ((this.ongetFormsInCompletedDelegate == null)) {
                this.ongetFormsInCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetFormsInCompleted);
            }
            base.InvokeAsync(this.onBegingetFormsInDelegate, new object[] {
                        ou}, this.onEndgetFormsInDelegate, this.ongetFormsInCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HAP.UserCard.Web.ResetPasswordResponse HAP.UserCard.Web.apiSoap.ResetPassword(HAP.UserCard.Web.ResetPasswordRequest request) {
            return base.Channel.ResetPassword(request);
        }
        
        public string ResetPassword(string username) {
            HAP.UserCard.Web.ResetPasswordRequest inValue = new HAP.UserCard.Web.ResetPasswordRequest();
            inValue.Body = new HAP.UserCard.Web.ResetPasswordRequestBody();
            inValue.Body.username = username;
            HAP.UserCard.Web.ResetPasswordResponse retVal = ((HAP.UserCard.Web.apiSoap)(this)).ResetPassword(inValue);
            return retVal.Body.ResetPasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HAP.UserCard.Web.apiSoap.BeginResetPassword(HAP.UserCard.Web.ResetPasswordRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginResetPassword(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginResetPassword(string username, System.AsyncCallback callback, object asyncState) {
            HAP.UserCard.Web.ResetPasswordRequest inValue = new HAP.UserCard.Web.ResetPasswordRequest();
            inValue.Body = new HAP.UserCard.Web.ResetPasswordRequestBody();
            inValue.Body.username = username;
            return ((HAP.UserCard.Web.apiSoap)(this)).BeginResetPassword(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HAP.UserCard.Web.ResetPasswordResponse HAP.UserCard.Web.apiSoap.EndResetPassword(System.IAsyncResult result) {
            return base.Channel.EndResetPassword(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndResetPassword(System.IAsyncResult result) {
            HAP.UserCard.Web.ResetPasswordResponse retVal = ((HAP.UserCard.Web.apiSoap)(this)).EndResetPassword(result);
            return retVal.Body.ResetPasswordResult;
        }
        
        private System.IAsyncResult OnBeginResetPassword(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            return this.BeginResetPassword(username, callback, asyncState);
        }
        
        private object[] OnEndResetPassword(System.IAsyncResult result) {
            string retVal = this.EndResetPassword(result);
            return new object[] {
                    retVal};
        }
        
        private void OnResetPasswordCompleted(object state) {
            if ((this.ResetPasswordCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ResetPasswordCompleted(this, new ResetPasswordCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ResetPasswordAsync(string username) {
            this.ResetPasswordAsync(username, null);
        }
        
        public void ResetPasswordAsync(string username, object userState) {
            if ((this.onBeginResetPasswordDelegate == null)) {
                this.onBeginResetPasswordDelegate = new BeginOperationDelegate(this.OnBeginResetPassword);
            }
            if ((this.onEndResetPasswordDelegate == null)) {
                this.onEndResetPasswordDelegate = new EndOperationDelegate(this.OnEndResetPassword);
            }
            if ((this.onResetPasswordCompletedDelegate == null)) {
                this.onResetPasswordCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnResetPasswordCompleted);
            }
            base.InvokeAsync(this.onBeginResetPasswordDelegate, new object[] {
                        username}, this.onEndResetPasswordDelegate, this.onResetPasswordCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HAP.UserCard.Web.GetFreeSpacePercentageResponse HAP.UserCard.Web.apiSoap.GetFreeSpacePercentage(HAP.UserCard.Web.GetFreeSpacePercentageRequest request) {
            return base.Channel.GetFreeSpacePercentage(request);
        }
        
        public HAP.UserCard.Web.QuotaInfo GetFreeSpacePercentage(string username, string userhome) {
            HAP.UserCard.Web.GetFreeSpacePercentageRequest inValue = new HAP.UserCard.Web.GetFreeSpacePercentageRequest();
            inValue.Body = new HAP.UserCard.Web.GetFreeSpacePercentageRequestBody();
            inValue.Body.username = username;
            inValue.Body.userhome = userhome;
            HAP.UserCard.Web.GetFreeSpacePercentageResponse retVal = ((HAP.UserCard.Web.apiSoap)(this)).GetFreeSpacePercentage(inValue);
            return retVal.Body.GetFreeSpacePercentageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HAP.UserCard.Web.apiSoap.BeginGetFreeSpacePercentage(HAP.UserCard.Web.GetFreeSpacePercentageRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetFreeSpacePercentage(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetFreeSpacePercentage(string username, string userhome, System.AsyncCallback callback, object asyncState) {
            HAP.UserCard.Web.GetFreeSpacePercentageRequest inValue = new HAP.UserCard.Web.GetFreeSpacePercentageRequest();
            inValue.Body = new HAP.UserCard.Web.GetFreeSpacePercentageRequestBody();
            inValue.Body.username = username;
            inValue.Body.userhome = userhome;
            return ((HAP.UserCard.Web.apiSoap)(this)).BeginGetFreeSpacePercentage(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HAP.UserCard.Web.GetFreeSpacePercentageResponse HAP.UserCard.Web.apiSoap.EndGetFreeSpacePercentage(System.IAsyncResult result) {
            return base.Channel.EndGetFreeSpacePercentage(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public HAP.UserCard.Web.QuotaInfo EndGetFreeSpacePercentage(System.IAsyncResult result) {
            HAP.UserCard.Web.GetFreeSpacePercentageResponse retVal = ((HAP.UserCard.Web.apiSoap)(this)).EndGetFreeSpacePercentage(result);
            return retVal.Body.GetFreeSpacePercentageResult;
        }
        
        private System.IAsyncResult OnBeginGetFreeSpacePercentage(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            string userhome = ((string)(inValues[1]));
            return this.BeginGetFreeSpacePercentage(username, userhome, callback, asyncState);
        }
        
        private object[] OnEndGetFreeSpacePercentage(System.IAsyncResult result) {
            HAP.UserCard.Web.QuotaInfo retVal = this.EndGetFreeSpacePercentage(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetFreeSpacePercentageCompleted(object state) {
            if ((this.GetFreeSpacePercentageCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetFreeSpacePercentageCompleted(this, new GetFreeSpacePercentageCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetFreeSpacePercentageAsync(string username, string userhome) {
            this.GetFreeSpacePercentageAsync(username, userhome, null);
        }
        
        public void GetFreeSpacePercentageAsync(string username, string userhome, object userState) {
            if ((this.onBeginGetFreeSpacePercentageDelegate == null)) {
                this.onBeginGetFreeSpacePercentageDelegate = new BeginOperationDelegate(this.OnBeginGetFreeSpacePercentage);
            }
            if ((this.onEndGetFreeSpacePercentageDelegate == null)) {
                this.onEndGetFreeSpacePercentageDelegate = new EndOperationDelegate(this.OnEndGetFreeSpacePercentage);
            }
            if ((this.onGetFreeSpacePercentageCompletedDelegate == null)) {
                this.onGetFreeSpacePercentageCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetFreeSpacePercentageCompleted);
            }
            base.InvokeAsync(this.onBeginGetFreeSpacePercentageDelegate, new object[] {
                        username,
                        userhome}, this.onEndGetFreeSpacePercentageDelegate, this.onGetFreeSpacePercentageCompletedDelegate, userState);
        }
    }
}
