//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAP.UserCard.Web {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Init", Namespace="http://hap.codeplex.com/")]
    [System.SerializableAttribute()]
    public partial class Init : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentGroupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ADConStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentEmailFormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StudentGroupName {
            get {
                return this.StudentGroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentGroupNameField, value) != true)) {
                    this.StudentGroupNameField = value;
                    this.RaisePropertyChanged("StudentGroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ADConString {
            get {
                return this.ADConStringField;
            }
            set {
                if ((object.ReferenceEquals(this.ADConStringField, value) != true)) {
                    this.ADConStringField = value;
                    this.RaisePropertyChanged("ADConString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string StudentEmailFormat {
            get {
                return this.StudentEmailFormatField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentEmailFormatField, value) != true)) {
                    this.StudentEmailFormatField = value;
                    this.RaisePropertyChanged("StudentEmailFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuotaInfo", Namespace="http://hap.codeplex.com/")]
    [System.SerializableAttribute()]
    public partial class QuotaInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HAP.UserCard.Web.ExtensionDataObject ExtensionData1Field;
        
        private double FreeField;
        
        private double TotalField;
        
        private double UsedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public HAP.UserCard.Web.ExtensionDataObject ExtensionData1 {
            get {
                return this.ExtensionData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionData1Field, value) != true)) {
                    this.ExtensionData1Field = value;
                    this.RaisePropertyChanged("ExtensionData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Free {
            get {
                return this.FreeField;
            }
            set {
                if ((this.FreeField.Equals(value) != true)) {
                    this.FreeField = value;
                    this.RaisePropertyChanged("Free");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Used {
            get {
                return this.UsedField;
            }
            set {
                if ((this.UsedField.Equals(value) != true)) {
                    this.UsedField = value;
                    this.RaisePropertyChanged("Used");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExtensionDataObject", Namespace="http://hap.codeplex.com/")]
    [System.SerializableAttribute()]
    public partial class ExtensionDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ticket", Namespace="http://hap.codeplex.com/")]
    [System.SerializableAttribute()]
    public partial class Ticket : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserField;
        
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HAP.UserCard.Web.Note[] NotesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Priority {
            get {
                return this.PriorityField;
            }
            set {
                if ((object.ReferenceEquals(this.PriorityField, value) != true)) {
                    this.PriorityField = value;
                    this.RaisePropertyChanged("Priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public HAP.UserCard.Web.Note[] Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Note", Namespace="http://hap.codeplex.com/")]
    [System.SerializableAttribute()]
    public partial class Note : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoteTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NoteText {
            get {
                return this.NoteTextField;
            }
            set {
                if ((object.ReferenceEquals(this.NoteTextField, value) != true)) {
                    this.NoteTextField = value;
                    this.RaisePropertyChanged("NoteText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://hap.codeplex.com/", ConfigurationName="Web.apiSoap")]
    public interface apiSoap {
        
        // CODEGEN: Generating message contract since element name getInitResult from namespace http://hap.codeplex.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://hap.codeplex.com/getInit", ReplyAction="*")]
        HAP.UserCard.Web.getInitResponse getInit(HAP.UserCard.Web.getInitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://hap.codeplex.com/getInit", ReplyAction="*")]
        System.IAsyncResult BegingetInit(HAP.UserCard.Web.getInitRequest request, System.AsyncCallback callback, object asyncState);
        
        HAP.UserCard.Web.getInitResponse EndgetInit(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name upn from namespace http://hap.codeplex.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://hap.codeplex.com/getPhoto", ReplyAction="*")]
        HAP.UserCard.Web.getPhotoResponse getPhoto(HAP.UserCard.Web.getPhotoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://hap.codeplex.com/getPhoto", ReplyAction="*")]
        System.IAsyncResult BegingetPhoto(HAP.UserCard.Web.getPhotoRequest request, System.AsyncCallback callback, object asyncState);
        
        HAP.UserCard.Web.getPhotoResponse EndgetPhoto(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name username from namespace http://hap.codeplex.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://hap.codeplex.com/GetFreeSpacePercentage", ReplyAction="*")]
        HAP.UserCard.Web.GetFreeSpacePercentageResponse GetFreeSpacePercentage(HAP.UserCard.Web.GetFreeSpacePercentageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://hap.codeplex.com/GetFreeSpacePercentage", ReplyAction="*")]
        System.IAsyncResult BeginGetFreeSpacePercentage(HAP.UserCard.Web.GetFreeSpacePercentageRequest request, System.AsyncCallback callback, object asyncState);
        
        HAP.UserCard.Web.GetFreeSpacePercentageResponse EndGetFreeSpacePercentage(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name username from namespace http://hap.codeplex.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://hap.codeplex.com/getMyTickets", ReplyAction="*")]
        HAP.UserCard.Web.getMyTicketsResponse getMyTickets(HAP.UserCard.Web.getMyTicketsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://hap.codeplex.com/getMyTickets", ReplyAction="*")]
        System.IAsyncResult BegingetMyTickets(HAP.UserCard.Web.getMyTicketsRequest request, System.AsyncCallback callback, object asyncState);
        
        HAP.UserCard.Web.getMyTicketsResponse EndgetMyTickets(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name subject from namespace http://hap.codeplex.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://hap.codeplex.com/setNewTicket", ReplyAction="*")]
        HAP.UserCard.Web.setNewTicketResponse setNewTicket(HAP.UserCard.Web.setNewTicketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://hap.codeplex.com/setNewTicket", ReplyAction="*")]
        System.IAsyncResult BeginsetNewTicket(HAP.UserCard.Web.setNewTicketRequest request, System.AsyncCallback callback, object asyncState);
        
        HAP.UserCard.Web.setNewTicketResponse EndsetNewTicket(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getInit", Namespace="http://hap.codeplex.com/", Order=0)]
        public HAP.UserCard.Web.getInitRequestBody Body;
        
        public getInitRequest() {
        }
        
        public getInitRequest(HAP.UserCard.Web.getInitRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getInitRequestBody {
        
        public getInitRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getInitResponse", Namespace="http://hap.codeplex.com/", Order=0)]
        public HAP.UserCard.Web.getInitResponseBody Body;
        
        public getInitResponse() {
        }
        
        public getInitResponse(HAP.UserCard.Web.getInitResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://hap.codeplex.com/")]
    public partial class getInitResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HAP.UserCard.Web.Init getInitResult;
        
        public getInitResponseBody() {
        }
        
        public getInitResponseBody(HAP.UserCard.Web.Init getInitResult) {
            this.getInitResult = getInitResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPhotoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPhoto", Namespace="http://hap.codeplex.com/", Order=0)]
        public HAP.UserCard.Web.getPhotoRequestBody Body;
        
        public getPhotoRequest() {
        }
        
        public getPhotoRequest(HAP.UserCard.Web.getPhotoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://hap.codeplex.com/")]
    public partial class getPhotoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string upn;
        
        public getPhotoRequestBody() {
        }
        
        public getPhotoRequestBody(string upn) {
            this.upn = upn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPhotoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPhotoResponse", Namespace="http://hap.codeplex.com/", Order=0)]
        public HAP.UserCard.Web.getPhotoResponseBody Body;
        
        public getPhotoResponse() {
        }
        
        public getPhotoResponse(HAP.UserCard.Web.getPhotoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://hap.codeplex.com/")]
    public partial class getPhotoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getPhotoResult;
        
        public getPhotoResponseBody() {
        }
        
        public getPhotoResponseBody(string getPhotoResult) {
            this.getPhotoResult = getPhotoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFreeSpacePercentageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFreeSpacePercentage", Namespace="http://hap.codeplex.com/", Order=0)]
        public HAP.UserCard.Web.GetFreeSpacePercentageRequestBody Body;
        
        public GetFreeSpacePercentageRequest() {
        }
        
        public GetFreeSpacePercentageRequest(HAP.UserCard.Web.GetFreeSpacePercentageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://hap.codeplex.com/")]
    public partial class GetFreeSpacePercentageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userhome;
        
        public GetFreeSpacePercentageRequestBody() {
        }
        
        public GetFreeSpacePercentageRequestBody(string username, string userhome) {
            this.username = username;
            this.userhome = userhome;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFreeSpacePercentageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFreeSpacePercentageResponse", Namespace="http://hap.codeplex.com/", Order=0)]
        public HAP.UserCard.Web.GetFreeSpacePercentageResponseBody Body;
        
        public GetFreeSpacePercentageResponse() {
        }
        
        public GetFreeSpacePercentageResponse(HAP.UserCard.Web.GetFreeSpacePercentageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://hap.codeplex.com/")]
    public partial class GetFreeSpacePercentageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HAP.UserCard.Web.QuotaInfo GetFreeSpacePercentageResult;
        
        public GetFreeSpacePercentageResponseBody() {
        }
        
        public GetFreeSpacePercentageResponseBody(HAP.UserCard.Web.QuotaInfo GetFreeSpacePercentageResult) {
            this.GetFreeSpacePercentageResult = GetFreeSpacePercentageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMyTicketsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMyTickets", Namespace="http://hap.codeplex.com/", Order=0)]
        public HAP.UserCard.Web.getMyTicketsRequestBody Body;
        
        public getMyTicketsRequest() {
        }
        
        public getMyTicketsRequest(HAP.UserCard.Web.getMyTicketsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://hap.codeplex.com/")]
    public partial class getMyTicketsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public getMyTicketsRequestBody() {
        }
        
        public getMyTicketsRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMyTicketsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMyTicketsResponse", Namespace="http://hap.codeplex.com/", Order=0)]
        public HAP.UserCard.Web.getMyTicketsResponseBody Body;
        
        public getMyTicketsResponse() {
        }
        
        public getMyTicketsResponse(HAP.UserCard.Web.getMyTicketsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://hap.codeplex.com/")]
    public partial class getMyTicketsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HAP.UserCard.Web.Ticket[] getMyTicketsResult;
        
        public getMyTicketsResponseBody() {
        }
        
        public getMyTicketsResponseBody(HAP.UserCard.Web.Ticket[] getMyTicketsResult) {
            this.getMyTicketsResult = getMyTicketsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setNewTicketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setNewTicket", Namespace="http://hap.codeplex.com/", Order=0)]
        public HAP.UserCard.Web.setNewTicketRequestBody Body;
        
        public setNewTicketRequest() {
        }
        
        public setNewTicketRequest(HAP.UserCard.Web.setNewTicketRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://hap.codeplex.com/")]
    public partial class setNewTicketRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string note;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string room;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string username;
        
        public setNewTicketRequestBody() {
        }
        
        public setNewTicketRequestBody(string subject, string note, string room, string username) {
            this.subject = subject;
            this.note = note;
            this.room = room;
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setNewTicketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setNewTicketResponse", Namespace="http://hap.codeplex.com/", Order=0)]
        public HAP.UserCard.Web.setNewTicketResponseBody Body;
        
        public setNewTicketResponse() {
        }
        
        public setNewTicketResponse(HAP.UserCard.Web.setNewTicketResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://hap.codeplex.com/")]
    public partial class setNewTicketResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HAP.UserCard.Web.Ticket[] setNewTicketResult;
        
        public setNewTicketResponseBody() {
        }
        
        public setNewTicketResponseBody(HAP.UserCard.Web.Ticket[] setNewTicketResult) {
            this.setNewTicketResult = setNewTicketResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface apiSoapChannel : HAP.UserCard.Web.apiSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getInitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getInitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HAP.UserCard.Web.Init Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HAP.UserCard.Web.Init)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getPhotoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getPhotoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetFreeSpacePercentageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetFreeSpacePercentageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HAP.UserCard.Web.QuotaInfo Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HAP.UserCard.Web.QuotaInfo)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getMyTicketsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getMyTicketsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HAP.UserCard.Web.Ticket[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HAP.UserCard.Web.Ticket[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class setNewTicketCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public setNewTicketCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HAP.UserCard.Web.Ticket[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HAP.UserCard.Web.Ticket[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class apiSoapClient : System.ServiceModel.ClientBase<HAP.UserCard.Web.apiSoap>, HAP.UserCard.Web.apiSoap {
        
        private BeginOperationDelegate onBegingetInitDelegate;
        
        private EndOperationDelegate onEndgetInitDelegate;
        
        private System.Threading.SendOrPostCallback ongetInitCompletedDelegate;
        
        private BeginOperationDelegate onBegingetPhotoDelegate;
        
        private EndOperationDelegate onEndgetPhotoDelegate;
        
        private System.Threading.SendOrPostCallback ongetPhotoCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetFreeSpacePercentageDelegate;
        
        private EndOperationDelegate onEndGetFreeSpacePercentageDelegate;
        
        private System.Threading.SendOrPostCallback onGetFreeSpacePercentageCompletedDelegate;
        
        private BeginOperationDelegate onBegingetMyTicketsDelegate;
        
        private EndOperationDelegate onEndgetMyTicketsDelegate;
        
        private System.Threading.SendOrPostCallback ongetMyTicketsCompletedDelegate;
        
        private BeginOperationDelegate onBeginsetNewTicketDelegate;
        
        private EndOperationDelegate onEndsetNewTicketDelegate;
        
        private System.Threading.SendOrPostCallback onsetNewTicketCompletedDelegate;
        
        public apiSoapClient() {
        }
        
        public apiSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public apiSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public apiSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public apiSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<getInitCompletedEventArgs> getInitCompleted;
        
        public event System.EventHandler<getPhotoCompletedEventArgs> getPhotoCompleted;
        
        public event System.EventHandler<GetFreeSpacePercentageCompletedEventArgs> GetFreeSpacePercentageCompleted;
        
        public event System.EventHandler<getMyTicketsCompletedEventArgs> getMyTicketsCompleted;
        
        public event System.EventHandler<setNewTicketCompletedEventArgs> setNewTicketCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HAP.UserCard.Web.getInitResponse HAP.UserCard.Web.apiSoap.getInit(HAP.UserCard.Web.getInitRequest request) {
            return base.Channel.getInit(request);
        }
        
        public HAP.UserCard.Web.Init getInit() {
            HAP.UserCard.Web.getInitRequest inValue = new HAP.UserCard.Web.getInitRequest();
            inValue.Body = new HAP.UserCard.Web.getInitRequestBody();
            HAP.UserCard.Web.getInitResponse retVal = ((HAP.UserCard.Web.apiSoap)(this)).getInit(inValue);
            return retVal.Body.getInitResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HAP.UserCard.Web.apiSoap.BegingetInit(HAP.UserCard.Web.getInitRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetInit(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegingetInit(System.AsyncCallback callback, object asyncState) {
            HAP.UserCard.Web.getInitRequest inValue = new HAP.UserCard.Web.getInitRequest();
            inValue.Body = new HAP.UserCard.Web.getInitRequestBody();
            return ((HAP.UserCard.Web.apiSoap)(this)).BegingetInit(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HAP.UserCard.Web.getInitResponse HAP.UserCard.Web.apiSoap.EndgetInit(System.IAsyncResult result) {
            return base.Channel.EndgetInit(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public HAP.UserCard.Web.Init EndgetInit(System.IAsyncResult result) {
            HAP.UserCard.Web.getInitResponse retVal = ((HAP.UserCard.Web.apiSoap)(this)).EndgetInit(result);
            return retVal.Body.getInitResult;
        }
        
        private System.IAsyncResult OnBegingetInit(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BegingetInit(callback, asyncState);
        }
        
        private object[] OnEndgetInit(System.IAsyncResult result) {
            HAP.UserCard.Web.Init retVal = this.EndgetInit(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetInitCompleted(object state) {
            if ((this.getInitCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getInitCompleted(this, new getInitCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getInitAsync() {
            this.getInitAsync(null);
        }
        
        public void getInitAsync(object userState) {
            if ((this.onBegingetInitDelegate == null)) {
                this.onBegingetInitDelegate = new BeginOperationDelegate(this.OnBegingetInit);
            }
            if ((this.onEndgetInitDelegate == null)) {
                this.onEndgetInitDelegate = new EndOperationDelegate(this.OnEndgetInit);
            }
            if ((this.ongetInitCompletedDelegate == null)) {
                this.ongetInitCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetInitCompleted);
            }
            base.InvokeAsync(this.onBegingetInitDelegate, null, this.onEndgetInitDelegate, this.ongetInitCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HAP.UserCard.Web.getPhotoResponse HAP.UserCard.Web.apiSoap.getPhoto(HAP.UserCard.Web.getPhotoRequest request) {
            return base.Channel.getPhoto(request);
        }
        
        public string getPhoto(string upn) {
            HAP.UserCard.Web.getPhotoRequest inValue = new HAP.UserCard.Web.getPhotoRequest();
            inValue.Body = new HAP.UserCard.Web.getPhotoRequestBody();
            inValue.Body.upn = upn;
            HAP.UserCard.Web.getPhotoResponse retVal = ((HAP.UserCard.Web.apiSoap)(this)).getPhoto(inValue);
            return retVal.Body.getPhotoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HAP.UserCard.Web.apiSoap.BegingetPhoto(HAP.UserCard.Web.getPhotoRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetPhoto(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegingetPhoto(string upn, System.AsyncCallback callback, object asyncState) {
            HAP.UserCard.Web.getPhotoRequest inValue = new HAP.UserCard.Web.getPhotoRequest();
            inValue.Body = new HAP.UserCard.Web.getPhotoRequestBody();
            inValue.Body.upn = upn;
            return ((HAP.UserCard.Web.apiSoap)(this)).BegingetPhoto(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HAP.UserCard.Web.getPhotoResponse HAP.UserCard.Web.apiSoap.EndgetPhoto(System.IAsyncResult result) {
            return base.Channel.EndgetPhoto(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndgetPhoto(System.IAsyncResult result) {
            HAP.UserCard.Web.getPhotoResponse retVal = ((HAP.UserCard.Web.apiSoap)(this)).EndgetPhoto(result);
            return retVal.Body.getPhotoResult;
        }
        
        private System.IAsyncResult OnBegingetPhoto(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string upn = ((string)(inValues[0]));
            return this.BegingetPhoto(upn, callback, asyncState);
        }
        
        private object[] OnEndgetPhoto(System.IAsyncResult result) {
            string retVal = this.EndgetPhoto(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetPhotoCompleted(object state) {
            if ((this.getPhotoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getPhotoCompleted(this, new getPhotoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getPhotoAsync(string upn) {
            this.getPhotoAsync(upn, null);
        }
        
        public void getPhotoAsync(string upn, object userState) {
            if ((this.onBegingetPhotoDelegate == null)) {
                this.onBegingetPhotoDelegate = new BeginOperationDelegate(this.OnBegingetPhoto);
            }
            if ((this.onEndgetPhotoDelegate == null)) {
                this.onEndgetPhotoDelegate = new EndOperationDelegate(this.OnEndgetPhoto);
            }
            if ((this.ongetPhotoCompletedDelegate == null)) {
                this.ongetPhotoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetPhotoCompleted);
            }
            base.InvokeAsync(this.onBegingetPhotoDelegate, new object[] {
                        upn}, this.onEndgetPhotoDelegate, this.ongetPhotoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HAP.UserCard.Web.GetFreeSpacePercentageResponse HAP.UserCard.Web.apiSoap.GetFreeSpacePercentage(HAP.UserCard.Web.GetFreeSpacePercentageRequest request) {
            return base.Channel.GetFreeSpacePercentage(request);
        }
        
        public HAP.UserCard.Web.QuotaInfo GetFreeSpacePercentage(string username, string userhome) {
            HAP.UserCard.Web.GetFreeSpacePercentageRequest inValue = new HAP.UserCard.Web.GetFreeSpacePercentageRequest();
            inValue.Body = new HAP.UserCard.Web.GetFreeSpacePercentageRequestBody();
            inValue.Body.username = username;
            inValue.Body.userhome = userhome;
            HAP.UserCard.Web.GetFreeSpacePercentageResponse retVal = ((HAP.UserCard.Web.apiSoap)(this)).GetFreeSpacePercentage(inValue);
            return retVal.Body.GetFreeSpacePercentageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HAP.UserCard.Web.apiSoap.BeginGetFreeSpacePercentage(HAP.UserCard.Web.GetFreeSpacePercentageRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetFreeSpacePercentage(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetFreeSpacePercentage(string username, string userhome, System.AsyncCallback callback, object asyncState) {
            HAP.UserCard.Web.GetFreeSpacePercentageRequest inValue = new HAP.UserCard.Web.GetFreeSpacePercentageRequest();
            inValue.Body = new HAP.UserCard.Web.GetFreeSpacePercentageRequestBody();
            inValue.Body.username = username;
            inValue.Body.userhome = userhome;
            return ((HAP.UserCard.Web.apiSoap)(this)).BeginGetFreeSpacePercentage(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HAP.UserCard.Web.GetFreeSpacePercentageResponse HAP.UserCard.Web.apiSoap.EndGetFreeSpacePercentage(System.IAsyncResult result) {
            return base.Channel.EndGetFreeSpacePercentage(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public HAP.UserCard.Web.QuotaInfo EndGetFreeSpacePercentage(System.IAsyncResult result) {
            HAP.UserCard.Web.GetFreeSpacePercentageResponse retVal = ((HAP.UserCard.Web.apiSoap)(this)).EndGetFreeSpacePercentage(result);
            return retVal.Body.GetFreeSpacePercentageResult;
        }
        
        private System.IAsyncResult OnBeginGetFreeSpacePercentage(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            string userhome = ((string)(inValues[1]));
            return this.BeginGetFreeSpacePercentage(username, userhome, callback, asyncState);
        }
        
        private object[] OnEndGetFreeSpacePercentage(System.IAsyncResult result) {
            HAP.UserCard.Web.QuotaInfo retVal = this.EndGetFreeSpacePercentage(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetFreeSpacePercentageCompleted(object state) {
            if ((this.GetFreeSpacePercentageCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetFreeSpacePercentageCompleted(this, new GetFreeSpacePercentageCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetFreeSpacePercentageAsync(string username, string userhome) {
            this.GetFreeSpacePercentageAsync(username, userhome, null);
        }
        
        public void GetFreeSpacePercentageAsync(string username, string userhome, object userState) {
            if ((this.onBeginGetFreeSpacePercentageDelegate == null)) {
                this.onBeginGetFreeSpacePercentageDelegate = new BeginOperationDelegate(this.OnBeginGetFreeSpacePercentage);
            }
            if ((this.onEndGetFreeSpacePercentageDelegate == null)) {
                this.onEndGetFreeSpacePercentageDelegate = new EndOperationDelegate(this.OnEndGetFreeSpacePercentage);
            }
            if ((this.onGetFreeSpacePercentageCompletedDelegate == null)) {
                this.onGetFreeSpacePercentageCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetFreeSpacePercentageCompleted);
            }
            base.InvokeAsync(this.onBeginGetFreeSpacePercentageDelegate, new object[] {
                        username,
                        userhome}, this.onEndGetFreeSpacePercentageDelegate, this.onGetFreeSpacePercentageCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HAP.UserCard.Web.getMyTicketsResponse HAP.UserCard.Web.apiSoap.getMyTickets(HAP.UserCard.Web.getMyTicketsRequest request) {
            return base.Channel.getMyTickets(request);
        }
        
        public HAP.UserCard.Web.Ticket[] getMyTickets(string username) {
            HAP.UserCard.Web.getMyTicketsRequest inValue = new HAP.UserCard.Web.getMyTicketsRequest();
            inValue.Body = new HAP.UserCard.Web.getMyTicketsRequestBody();
            inValue.Body.username = username;
            HAP.UserCard.Web.getMyTicketsResponse retVal = ((HAP.UserCard.Web.apiSoap)(this)).getMyTickets(inValue);
            return retVal.Body.getMyTicketsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HAP.UserCard.Web.apiSoap.BegingetMyTickets(HAP.UserCard.Web.getMyTicketsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetMyTickets(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegingetMyTickets(string username, System.AsyncCallback callback, object asyncState) {
            HAP.UserCard.Web.getMyTicketsRequest inValue = new HAP.UserCard.Web.getMyTicketsRequest();
            inValue.Body = new HAP.UserCard.Web.getMyTicketsRequestBody();
            inValue.Body.username = username;
            return ((HAP.UserCard.Web.apiSoap)(this)).BegingetMyTickets(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HAP.UserCard.Web.getMyTicketsResponse HAP.UserCard.Web.apiSoap.EndgetMyTickets(System.IAsyncResult result) {
            return base.Channel.EndgetMyTickets(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public HAP.UserCard.Web.Ticket[] EndgetMyTickets(System.IAsyncResult result) {
            HAP.UserCard.Web.getMyTicketsResponse retVal = ((HAP.UserCard.Web.apiSoap)(this)).EndgetMyTickets(result);
            return retVal.Body.getMyTicketsResult;
        }
        
        private System.IAsyncResult OnBegingetMyTickets(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            return this.BegingetMyTickets(username, callback, asyncState);
        }
        
        private object[] OnEndgetMyTickets(System.IAsyncResult result) {
            HAP.UserCard.Web.Ticket[] retVal = this.EndgetMyTickets(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetMyTicketsCompleted(object state) {
            if ((this.getMyTicketsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getMyTicketsCompleted(this, new getMyTicketsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getMyTicketsAsync(string username) {
            this.getMyTicketsAsync(username, null);
        }
        
        public void getMyTicketsAsync(string username, object userState) {
            if ((this.onBegingetMyTicketsDelegate == null)) {
                this.onBegingetMyTicketsDelegate = new BeginOperationDelegate(this.OnBegingetMyTickets);
            }
            if ((this.onEndgetMyTicketsDelegate == null)) {
                this.onEndgetMyTicketsDelegate = new EndOperationDelegate(this.OnEndgetMyTickets);
            }
            if ((this.ongetMyTicketsCompletedDelegate == null)) {
                this.ongetMyTicketsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetMyTicketsCompleted);
            }
            base.InvokeAsync(this.onBegingetMyTicketsDelegate, new object[] {
                        username}, this.onEndgetMyTicketsDelegate, this.ongetMyTicketsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HAP.UserCard.Web.setNewTicketResponse HAP.UserCard.Web.apiSoap.setNewTicket(HAP.UserCard.Web.setNewTicketRequest request) {
            return base.Channel.setNewTicket(request);
        }
        
        public HAP.UserCard.Web.Ticket[] setNewTicket(string subject, string note, string room, string username) {
            HAP.UserCard.Web.setNewTicketRequest inValue = new HAP.UserCard.Web.setNewTicketRequest();
            inValue.Body = new HAP.UserCard.Web.setNewTicketRequestBody();
            inValue.Body.subject = subject;
            inValue.Body.note = note;
            inValue.Body.room = room;
            inValue.Body.username = username;
            HAP.UserCard.Web.setNewTicketResponse retVal = ((HAP.UserCard.Web.apiSoap)(this)).setNewTicket(inValue);
            return retVal.Body.setNewTicketResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HAP.UserCard.Web.apiSoap.BeginsetNewTicket(HAP.UserCard.Web.setNewTicketRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginsetNewTicket(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginsetNewTicket(string subject, string note, string room, string username, System.AsyncCallback callback, object asyncState) {
            HAP.UserCard.Web.setNewTicketRequest inValue = new HAP.UserCard.Web.setNewTicketRequest();
            inValue.Body = new HAP.UserCard.Web.setNewTicketRequestBody();
            inValue.Body.subject = subject;
            inValue.Body.note = note;
            inValue.Body.room = room;
            inValue.Body.username = username;
            return ((HAP.UserCard.Web.apiSoap)(this)).BeginsetNewTicket(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HAP.UserCard.Web.setNewTicketResponse HAP.UserCard.Web.apiSoap.EndsetNewTicket(System.IAsyncResult result) {
            return base.Channel.EndsetNewTicket(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public HAP.UserCard.Web.Ticket[] EndsetNewTicket(System.IAsyncResult result) {
            HAP.UserCard.Web.setNewTicketResponse retVal = ((HAP.UserCard.Web.apiSoap)(this)).EndsetNewTicket(result);
            return retVal.Body.setNewTicketResult;
        }
        
        private System.IAsyncResult OnBeginsetNewTicket(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string subject = ((string)(inValues[0]));
            string note = ((string)(inValues[1]));
            string room = ((string)(inValues[2]));
            string username = ((string)(inValues[3]));
            return this.BeginsetNewTicket(subject, note, room, username, callback, asyncState);
        }
        
        private object[] OnEndsetNewTicket(System.IAsyncResult result) {
            HAP.UserCard.Web.Ticket[] retVal = this.EndsetNewTicket(result);
            return new object[] {
                    retVal};
        }
        
        private void OnsetNewTicketCompleted(object state) {
            if ((this.setNewTicketCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.setNewTicketCompleted(this, new setNewTicketCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void setNewTicketAsync(string subject, string note, string room, string username) {
            this.setNewTicketAsync(subject, note, room, username, null);
        }
        
        public void setNewTicketAsync(string subject, string note, string room, string username, object userState) {
            if ((this.onBeginsetNewTicketDelegate == null)) {
                this.onBeginsetNewTicketDelegate = new BeginOperationDelegate(this.OnBeginsetNewTicket);
            }
            if ((this.onEndsetNewTicketDelegate == null)) {
                this.onEndsetNewTicketDelegate = new EndOperationDelegate(this.OnEndsetNewTicket);
            }
            if ((this.onsetNewTicketCompletedDelegate == null)) {
                this.onsetNewTicketCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnsetNewTicketCompleted);
            }
            base.InvokeAsync(this.onBeginsetNewTicketDelegate, new object[] {
                        subject,
                        note,
                        room,
                        username}, this.onEndsetNewTicketDelegate, this.onsetNewTicketCompletedDelegate, userState);
        }
    }
}
